site_name: Informatik Unterrichtsskript
site_url: https://transparenz.hilberg.eu/
theme:
  name: material
  language: de
markdown_extensions:
  - pymdownx.snippets
  - mdx_math:
      enable_dollar_delimiter: True
plugins:
  - macros
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: true
      caption_position: bottom
      background: white
      shadow: true
      manual: false

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  version:
      provider: mike
      default: latest
  commit_hash: !ENV REPO_COMMIT
  github_user: tna76874
  github_repo: informatik_skripte
  build_doc_date: !ENV build_doc_date
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tna76874/informatik_skripte
      name: "tna76874"
  urls:
    docfile: files/skript.pdf

copyright: !ENV build_doc_date

nav:
  - Skript: index.md
  - Links: links.md